name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
    - uses: actions/upload-artifact@v2
      with:
        name: xmrig-ubuntu
        path: ./build
